FROM ruby:3.2-slim

WORKDIR /app
COPY Gemfile LICENSE notes_cloud_ripper.rb ./
COPY lib/ /app/lib
RUN apt update && \
	apt-get install -y build-essential pkg-config libsqlite3-dev zlib1g-dev && \
	bundle config set force_ruby_platform true && \
	bundle install && \
	apt-get remove -y build-essential pkg-config && \
	apt autoremove -y 
ENTRYPOINT ["ruby", "notes_cloud_ripper.rb"]
