# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notestore.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("notestore.proto", :syntax => :proto2) do
    add_message "Color" do
      required :red, :float, 1
      required :green, :float, 2
      required :blue, :float, 3
      required :alpha, :float, 4
    end
    add_message "AttachmentInfo" do
      optional :attachment_identifier, :string, 1
      optional :type_uti, :string, 2
    end
    add_message "Font" do
      optional :font_name, :string, 1
      optional :point_size, :float, 2
      optional :font_hints, :int32, 3
    end
    add_message "ParagraphStyle" do
      optional :style_type, :int32, 1, default: -1
      optional :alignment, :int32, 2
      optional :indent_amount, :int32, 4
      optional :checklist, :message, 5, "Checklist"
    end
    add_message "Checklist" do
      required :uuid, :bytes, 1
      required :done, :int32, 2
    end
    add_message "DictionaryElement" do
      required :key, :message, 1, "ObjectID"
      required :value, :message, 2, "ObjectID"
    end
    add_message "Dictionary" do
      repeated :element, :message, 1, "DictionaryElement"
    end
    add_message "ObjectID" do
      required :unsigned_integer_value, :uint64, 2
      required :string_value, :string, 4
      required :object_index, :int32, 6
    end
    add_message "RegisterLatest" do
      required :contents, :message, 2, "ObjectID"
    end
    add_message "MapEntry" do
      required :key, :int32, 1
      required :value, :message, 2, "ObjectID"
    end
    add_message "AttributeRun" do
      required :length, :int32, 1
      optional :paragraph_style, :message, 2, "ParagraphStyle"
      optional :font, :message, 3, "Font"
      optional :font_weight, :int32, 5
      optional :underlined, :int32, 6
      optional :strikethrough, :int32, 7
      optional :superscript, :int32, 8
      optional :link, :string, 9
      optional :color, :message, 10, "Color"
      optional :attachment_info, :message, 12, "AttachmentInfo"
    end
    add_message "NoteStoreProto" do
      required :unknown_1, :int32, 1
      required :document, :message, 2, "Document"
    end
    add_message "Document" do
      required :unknown_1, :int32, 1
      required :version, :int32, 2
      required :note, :message, 3, "Note"
    end
    add_message "Note" do
      required :note_text, :string, 2
      repeated :attribute_run, :message, 5, "AttributeRun"
    end
    add_message "MergableDataProto" do
      required :unknown_1, :int32, 1
      required :mergable_data_object, :message, 2, "MergableDataObject"
    end
    add_message "MergableDataObject" do
      required :unknown_1, :int32, 1
      required :version, :int32, 2
      required :mergeable_data_object_data, :message, 3, "MergeableDataObjectData"
    end
    add_message "MergeableDataObjectData" do
      repeated :mergeable_data_object_entry, :message, 3, "MergeableDataObjectEntry"
      repeated :mergeable_data_object_key_item, :string, 4
      repeated :mergeable_data_object_type_item, :string, 5
      repeated :mergeable_data_object_uuid_item, :bytes, 6
    end
    add_message "MergeableDataObjectEntry" do
      required :register_latest, :message, 1, "RegisterLatest"
      optional :dictionary, :message, 6, "Dictionary"
      optional :note, :message, 10, "Note"
      optional :custom_map, :message, 13, "MergeableDataObjectMap"
      optional :ordered_set, :message, 16, "OrderedSet"
    end
    add_message "MergeableDataObjectMap" do
      required :type, :int32, 1
      repeated :map_entry, :message, 3, "MapEntry"
    end
    add_message "OrderedSet" do
      required :ordering, :message, 1, "OrderedSetOrdering"
      required :elements, :message, 2, "Dictionary"
    end
    add_message "OrderedSetOrdering" do
      required :array, :message, 1, "OrderedSetOrderingArray"
      required :contents, :message, 2, "Dictionary"
    end
    add_message "OrderedSetOrderingArray" do
      required :contents, :message, 1, "Note"
      repeated :attachment, :message, 2, "OrderedSetOrderingArrayAttachment"
    end
    add_message "OrderedSetOrderingArrayAttachment" do
      required :index, :int32, 1
      required :uuid, :bytes, 2
    end
  end
end

Color = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Color").msgclass
AttachmentInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AttachmentInfo").msgclass
Font = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Font").msgclass
ParagraphStyle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ParagraphStyle").msgclass
Checklist = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Checklist").msgclass
DictionaryElement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DictionaryElement").msgclass
Dictionary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Dictionary").msgclass
ObjectID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ObjectID").msgclass
RegisterLatest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RegisterLatest").msgclass
MapEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MapEntry").msgclass
AttributeRun = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AttributeRun").msgclass
NoteStoreProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NoteStoreProto").msgclass
Document = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Document").msgclass
Note = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Note").msgclass
MergableDataProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MergableDataProto").msgclass
MergableDataObject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MergableDataObject").msgclass
MergeableDataObjectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MergeableDataObjectData").msgclass
MergeableDataObjectEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MergeableDataObjectEntry").msgclass
MergeableDataObjectMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MergeableDataObjectMap").msgclass
OrderedSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderedSet").msgclass
OrderedSetOrdering = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderedSetOrdering").msgclass
OrderedSetOrderingArray = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderedSetOrderingArray").msgclass
OrderedSetOrderingArrayAttachment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderedSetOrderingArrayAttachment").msgclass
